// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AptInsert: typeof import('./components/management/AptInsert.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    Basic: typeof import('./components/building/Basic.vue')['default']
    Charger: typeof import('./components/building/Charger.vue')['default']
    CheckMenu: typeof import('./components/layouts/CheckMenu.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    Ess: typeof import('./components/building/Ess.vue')['default']
    FacilityInsert: typeof import('./components/management/FacilityInsert.vue')['default']
    Fuel: typeof import('./components/building/Fuel.vue')['default']
    Generator: typeof import('./components/building/Generator.vue')['default']
    InquiryInsert: typeof import('./components/management/InquiryInsert.vue')['default']
    ManagementMenu: typeof import('./components/layouts/ManagementMenu.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    Sunlight: typeof import('./components/building/Sunlight.vue')['default']
    TiptapEditor: typeof import('./components/TiptapEditor.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    TotalDiv: typeof import('./components/TotalDiv.vue')['default']
    Ups: typeof import('./components/building/Ups.vue')['default']
    Water: typeof import('./components/building/Water.vue')['default']
    Wind: typeof import('./components/building/Wind.vue')['default']
    YTable: typeof import('./components/YTable.vue')['default']
    YTd: typeof import('./components/YTd.vue')['default']
    YTh: typeof import('./components/YTh.vue')['default']
    YTr: typeof import('./components/YTr.vue')['default']
  }
}

export { }
