// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AptInsert: typeof import('./components/management/AptInsert.vue')['default']
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    InquiryInsert: typeof import('./components/management/InquiryInsert.vue')['default']
    ManagementSettingMenu: typeof import('./components/layouts/ManagementSettingMenu.vue')['default']
    PageTitle: typeof import('./components/PageTitle.vue')['default']
    TiptapEditor: typeof import('./components/TiptapEditor.vue')['default']
    Title: typeof import('./components/layouts/Title.vue')['default']
    TotalDiv: typeof import('./components/TotalDiv.vue')['default']
    YTable: typeof import('./components/YTable.vue')['default']
    YTd: typeof import('./components/YTd.vue')['default']
    YTh: typeof import('./components/YTh.vue')['default']
    YTr: typeof import('./components/YTr.vue')['default']
  }
}

export { }
